import {
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CalendarX,
  Clock3,
  Download,
  FolderKanban,
  Home,
  MapPinned,
  MoreHorizontal,
  ShieldCheck,
  Users,
} from "lucide-react";

import type { NavigationItem } from "../types/navigation";

export const navigationItems: NavigationItem[] = [
  {
    label: "Übersicht",
    path: "/",
    icon: Home,
    roles: ["admin", "project_manager", "office", "monteur"],
    officePermission: "overview",
  },
  {
    label: "Baustellenkalender",
    path: "/matrix",
    icon: CalendarDays,
    roles: ["admin", "project_manager", "office"],
    officePermission: "calendar",
  },
  {
    label: "Abwesenheiten",
    path: "/absences",
    icon: CalendarX,
    roles: ["admin", "project_manager", "office"],
    officePermission: "absences",
  },
  {
    label: "Baustellen",
    path: "/sites",
    icon: BriefcaseBusiness,
    roles: ["admin", "project_manager", "office"],
    officePermission: "sites",
  },
  {
    label: "Kartenübersicht",
    path: "/site-map",
    icon: MapPinned,
    roles: ["admin", "project_manager", "office"],
    officePermission: "map",
  },
  {
    label: "Lohnprüfung",
    path: "/time-entries",
    icon: Clock3,
    roles: ["admin", "project_manager", "office"],
    officePermission: "payroll",
  },
  {
    label: "Kunden",
    path: "/customers",
    icon: Building2,
    roles: ["admin", "project_manager", "office"],
    officePermission: "customers",
  },
  {
    label: "Mitarbeiter",
    path: "/persons",
    icon: Users,
    roles: ["admin", "project_manager", "office"],
    officePermission: "employees",
  },
  {
    label: "Export",
    path: "/exports",
    icon: Download,
    roles: ["admin", "project_manager", "office"],
    officePermission: "export",
  },
  {
    label: "Sonstige",
    path: "/sonstige",
    icon: MoreHorizontal,
    roles: ["admin"],
    adminOnly: true,
  },
  {
    label: "Benutzer (admin)",
    path: "/users",
    icon: ShieldCheck,
    roles: ["admin"],
    adminOnly: true,
  },
  {
    label: "Meine Einsaetze",
    path: "/me/assignments",
    icon: FolderKanban,
    roles: ["monteur"],
  },
];
